# Generated by Django 3.0.5 on 2020-06-26 15:13

from django.db import migrations, models
import django.db.models.deletion


def init_favorite_workspace(app, kwargs):
    user_model = app.get_model('gui', 'teamlockuser')
    workspace_model = app.get_model('gui', 'workspace')

    for user in user_model.objects.all().exclude(email="backup@teamlock.io"):
        workspace = workspace_model.objects.get(owner=user, name="Personal")
        user.favorite_workspace = workspace
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_auto_20200411_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlockuser',
            name='favorite_workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gui.Workspace'),
        ),
        migrations.RunPython(init_favorite_workspace, migrations.RunPython.noop)
    ]
